[project]
name = "uv-cdk-demo"
version = "0.1.0"

[tool.uv.workspace]
members = ["packages/*", "cdk"]

[dependency-groups]
dev = [
    "ruff>=0.8.4",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "W", "I"]
